CREATE DATABASE IF NOT EXISTS jttrackerdb;
CREATE DATABASE IF NOT EXISTS test;
ALTER DATABASE test DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;
ALTER DATABASE jttrackerdb DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;
USE jttrackerdb;
--CREATE USER 'test'@'%' IDENTIFIED BY 'password';
--GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `test`.* TO 'test'@'%';

--FLUSH PRIVILEGES;