version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/frontend/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - ervin joa
    assignees:
      - ervin joa
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `maven` packages
  - package-ecosystem: "maven" 
    directory: "/" # Location of package manifests
    schedule:
     interval: "daily"
    open-pull-requests-limit: 10     
    reviewers:
     - ervin joa
    assignees:
     - ervin joa
    commit-message:
     prefix: fix
     prefix-development: chore
     include: scope
