version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/frontend/'
    schedule:
      interval: daily
      time: '12:30'
    open-pull-requests-limit: 10
    reviewers:
      - ervin joa
    assignees:
      - ervin joa
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `maven` packages
  - package-ecosystem: maven 
    directory: "/"
    schedule:
      interval: "daily"
      time: '12:30'
    open-pull-requests-limit: 10     
    reviewers:
      - ervin joa
    assignees:
      - ervin joa
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `docker` packages
  - package-ecosystem: docker 
    directory: "/"
    schedule:
      interval: "daily"
      time: '12:30'
    open-pull-requests-limit: 10     
    reviewers:
      - ervin joa
    assignees:
      - ervin joa
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
