spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
logging.level.root=INFO
logging.level.ee.desertgun.jttracker=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
spring.datasource.username=test
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop