name: docker-compose-actions-workflow
on: push
jobs:
  app-deployment-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dockercompose build
        run: docker-compose up -d
      - name: App deployment test
        run: docker run --network container:springboot